swagger: "2.0"
info:
  description: "LiveOrg api"
  version: "0.1.0"
  title: "LiveOrg"
schemes:
- http
produces:
  - application/json
paths:
  /races:
    get:
      tags:
        - Race
      summary: Get races
      parameters:
        - $ref: '#/parameters/offsetParam'
        - $ref: '#/parameters/limitParam'
      responses:
        200:
          description: OK
          schema:
            items:
              $ref: '#/definitions/Race'
            type: array
  /race:
    post:
      tags:
        - Race
      summary: Create new race
      parameters:
        - in: body
          name: race
          required: true
          schema:
            $ref: '#/definitions/NewRace'
      responses:
        201:
          description: OK
          schema:
            $ref: '#/definitions/Race'
  /race/{race_id}:
    get:
      tags:
        - Race
      summary: Get race
      parameters:
        - $ref: '#/parameters/racePath'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Race'
    put:
      tags:
        - Race
      summary: Update race
      parameters:
        - $ref: '#/parameters/racePath'
        - in: body
          name: race
          required: true
          schema:
            $ref: '#/definitions/NewRace'
      responses:
        201:
          description: OK
          schema:
            $ref: '#/definitions/Race'
    delete:
      tags:
        - Race
      summary: Delete race
      parameters:
        - $ref: '#/parameters/racePath'
      responses:
        204:
          description: OK

  /group:
    post:
      tags:
        - Group
      summary: Create group
      parameters:
        - in: body
          name: group
          required: true
          schema:
            $ref: '#/definitions/NewGroup'
      responses:
        201:
          description: OK
          schema:
            $ref: '#/definitions/Group'
  /group/{group_id}:
    put:
      tags:
        - Group
      summary: Update group
      parameters:
        - $ref: '#/parameters/groupPath'
        - in: body
          name: group
          required: true
          schema:
            $ref: '#/definitions/NewGroup'
      responses:
        201:
          description: OK
          schema:
            $ref: '#/definitions/Group'
    delete:
      tags:
        - Group
      summary: Delete group
      parameters:
        - $ref: '#/parameters/groupPath'
      responses:
        204:
          description: OK


definitions:
  NewRace:
    type: object
    required:
      - name
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
      description:
        type: string
  Race:
    allOf:
    - $ref: '#/definitions/NewRace'
    - type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid
  NewGroup:
    type: object
    required:
      - race_id
      - name
    properties:
      id:
        type: string
        format: uuid
      race_id:
        type: string
        format: uuid
      name:
        type: string
      description:
        type: string
  Group:
    allOf:
    - $ref: '#/definitions/NewGroup'
    - type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid


parameters:
  racePath:
    name: race_id
    in: path
    type: string
    format: uuid
    required: true
  groupPath:
    name: group_id
    in: path
    type: string
    format: uuid
    required: true
  offsetParam:
    name: offset
    in: query
    type: integer
    format: int32
    default: 0
    required: true
  limitParam:
    name: limit
    in: query
    type: integer
    format: int32
    default: 20
    required: true