swagger: "2.0"
info:
  description: "LiveOrg api"
  version: "0.1.0"
  title: "LiveOrg"
schemes:
- http
produces:
  - application/json
paths:
  /races:
    get:
      tags:
        - Race
      summary: Get races
      parameters:
        - $ref: '#/parameters/offsetParam'
        - $ref: '#/parameters/limitParam'
      responses:
        200:
          description: OK
          schema:
            items:
              $ref: '#/definitions/Race'
            type: array
  /race:
    post:
      tags:
        - Race
      summary: Create new race
      parameters:
        - in: body
          name: race
          required: true
          schema:
            $ref: '#/definitions/Race'
      responses:
        201:
          description: OK
          schema:
            $ref: '#/definitions/Race'
    put:
      tags:
        - Race
      summary: Update race
      parameters:
        - in: body
          name: race
          required: true
          schema:
            $ref: '#/definitions/Race'
      responses:
        201:
          description: OK
          schema:
            $ref: '#/definitions/Race'
  /race/{race_id}:
    get:
      tags:
        - Race
      summary: Get race
      parameters:
        - $ref: '#/parameters/racePath'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Race'
    delete:
      tags:
        - Race
      summary: Delete race
      parameters:
        - $ref: '#/parameters/racePath'
      responses:
        204:
          description: OK

  /groups:
    get:
      tags:
        - Group
      summary: Get groups
      parameters:
        - in: query
          name: race_id
          type: string
          format: uuid
          required: false
      responses:
        200:
          description: OK
          schema:
            items:
              $ref: '#/definitions/Group'
            type: array
    post:
      tags:
        - Group
      summary: Create groups
      parameters:
        - in: body
          name: groups
          required: true
          schema:
            items:
              $ref: '#/definitions/Group'
            type: array
      responses:
        201:
          description: OK
          schema:
            items:
              $ref: '#/definitions/Group'
            type: array
    put:
      tags:
        - Group
      summary: Update groups
      parameters:
        - in: body
          name: groups
          required: true
          schema:
            items:
              $ref: '#/definitions/Group'
            type: array
      responses:
        201:
          description: OK
          schema:
            items:
              $ref: '#/definitions/Group'
            type: array
  /group:
    post:
      tags:
        - Group
      summary: Create group
      parameters:
        - in: body
          name: group
          required: true
          schema:
            $ref: '#/definitions/Group'
      responses:
        201:
          description: OK
          schema:
            $ref: '#/definitions/Group'
    put:
      tags:
        - Group
      summary: Update group
      parameters:
        - in: body
          name: group
          required: true
          schema:
            $ref: '#/definitions/Group'
      responses:
        201:
          description: OK
          schema:
            $ref: '#/definitions/Group'
  /group/{group_id}:
    get:
      tags:
        - Group
      summary: Get group
      parameters:
        - $ref: '#/parameters/groupPath'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Group'
    delete:
      tags:
        - Group
      summary: Delete group
      parameters:
        - $ref: '#/parameters/groupPath'
      responses:
        204:
          description: OK

  /persons:
    get:
      tags:
        - Person
      summary: Get persons
      parameters:
        - in: query
          name: race_id
          type: string
          format: uuid
          required: false
        - in: query
          name: group_id
          type: string
          format: uuid
          required: false
      responses:
        200:
          description: OK
          schema:
            items:
              $ref: '#/definitions/Person'
            type: array
    post:
      tags:
        - Person
      summary: Create persons
      parameters:
        - in: body
          name: persons
          required: true
          schema:
            items:
              $ref: '#/definitions/Person'
            type: array
      responses:
        201:
          description: OK
          schema:
            items:
              $ref: '#/definitions/Person'
            type: array
    put:
      tags:
        - Person
      summary: Update persons
      parameters:
        - in: body
          name: persons
          required: true
          schema:
            items:
              $ref: '#/definitions/Person'
            type: array
      responses:
        201:
          description: OK
          schema:
            items:
              $ref: '#/definitions/Person'
            type: array
  /person:
    post:
      tags:
        - Person
      summary: Create person
      parameters:
        - in: body
          name: person
          required: true
          schema:
            $ref: '#/definitions/Person'
      responses:
        201:
          description: OK
          schema:
            $ref: '#/definitions/Person'
    put:
      tags:
        - Person
      summary: Update person
      parameters:
        - in: body
          name: person
          required: true
          schema:
            $ref: '#/definitions/Person'
      responses:
        201:
          description: OK
          schema:
            $ref: '#/definitions/Person'
  /person/{person_id}:
    delete:
      tags:
        - Person
      summary: Delete person
      parameters:
        - $ref: '#/parameters/personPath'
      responses:
        204:
          description: OK

definitions:
  Race:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
      description:
        type: string
      start_date:
        type: string
        format: date-time
      end_date:
        type: string
        format: date-time
      timezone:
        type: number
        default: 0
        minimum: -12
        maximum: +12
  Course:
    type: object
    properties:
      code:
        type: string
  Group:
    type: object
    required:
      - id
      - race_id
      - name
    properties:
      id:
        type: string
        format: uuid
      race_id:
        type: string
        format: uuid
      name:
        type: string
      description:
        type: string
      course:
        items:
          $ref: '#/definitions/Course'
        type: array
  Split:
    type: object
    properties:
      code:
        type: string
      time:
        type: number # msec
  Person:
    type: object
    required:
      - id
      - group_id
      - name
    properties:
      id:
        type: string
        format: uuid
      group_id:
        type: string
        format: uuid
      name:
        type: string
      description:
        type: string
      link:
        type: string
        format: url
      team:
        type: string
      start:
        type: string
        format: date-time
      finish:
        type: string
        format: date-time
      result:
        type: number # msec
      split:
        items:
          $ref: '#/definitions/Split'
        type: array
      status:
        type: string
        enum:
          - OK
          - DSQ


parameters:
  racePath:
    name: race_id
    in: path
    type: string
    format: uuid
    required: true
  groupPath:
    name: group_id
    in: path
    type: string
    format: uuid
    required: true
  personPath:
    name: person_id
    in: path
    type: string
    format: uuid
    required: true
  offsetParam:
    name: offset
    in: query
    type: integer
    format: int32
    default: 0
    required: true
  limitParam:
    name: limit
    in: query
    type: integer
    format: int32
    default: 20
    required: true